### ISSUE TITLE
Dataset Download

### ISSUE THREAD

**Issue by stephen9999999** [arclab-hku/ecmd#1]
Hi, I am interested in your dataset, may I ask where I can download the dataset? And could you provide related paper link? Thanks.

**Comment by KwanWaiPang** [comment]
Thank you for your interest in our work. 
Once the paper is accepted,  we will release all the datasets and keep the dataset maintenance.
You can find the preprint version of our paper at https://arxiv.org/abs/2311.02327

**Comment by cpymaple** [comment]
Hi, we have released some sequences on our website "Download" page.
