### ISSUE TITLE
Thermal Camera Calibration

### ISSUE THREAD

**Issue by hogyun2** [arclab-hku/ecmd#10]
Thank you for publishing great works.

I have a question about thermal camera calibration parameters.
I use an equation (LiDAR to IMU) * (Thermal to IMU).T, but the LiDAR point cloud doesn't project fit in the thermal image. 

I changed the Thermal to IMU matrix below, and then it appears to be a better match.
 :
[-0.004737095204842272, 0.00440237743476074, -0.9999790892823434, -0.016708401512498278],
[-0.9999870322291338, 0.0018904303748249727, -0.0047288102700693765, 0.93310017262785824],
[-0.001869572836942935, 0.999988522607096, 0.004411275494402622, -0.2494544692614457],
[0.0, 0.0, 0.0, 1.0]

Could you check the parameters?

**Comment by cpymaple** [comment]
Hi, thanks for your interest.

1. It seems that you use the wrong equation to calculate the transformation between Lidar and Thermal camera. The equation should be " T_Lidar_to_Thermal = T_IMU_to_Thermal * T_Lidar_to_IMU ".  Maybe you can try to re-calculate the extrinsic between Lidar and Thermal camera.

2. Which Lidar you use (Center, Left or Right)? And could you provide the matching image shows " the LiDAR point cloud doesn't project fit in the thermal image. " ? 

3. We also provide the calibration bag, maybe you can have a try.

**Comment by cpymaple** [comment]
> Thank you for publishing great works.
> 
> I have a question about thermal camera calibration parameters. I use an equation (LiDAR to IMU) * (Thermal to IMU).T, but the LiDAR point cloud doesn't project fit in the thermal image.
> 
> I changed the Thermal to IMU matrix below, and then it appears to be a better match. : [-0.004737095204842272, 0.00440237743476074, -0.9999790892823434, -0.016708401512498278], [-0.9999870322291338, 0.0018904303748249727, -0.0047288102700693765, 0.93310017262785824], [-0.001869572836942935, 0.999988522607096, 0.004411275494402622, -0.2494544692614457], [0.0, 0.0, 0.0, 1.0]
> 
> Could you check the parameters?

Hi, thanks for your interest.

1. It seems that you use the wrong equation to calculate the transformation between Lidar and Thermal camera. The equation should be " T_Lidar_to_Thermal = T_IMU_to_Thermal * T_Lidar_to_IMU ".  Maybe you can try to re-calculate the extrinsic between Lidar and Thermal camera.

2. Which Lidar you use (Center, Left or Right)? And could you provide the matching image shows " the LiDAR point cloud doesn't project fit in the thermal image. " ? 

3. We also provide the calibration bag, maybe you can have a try.
