### ISSUE TITLE
sensor_msgs/CompressedImage

### ISSUE THREAD

**Issue by coolaogege** [arclab-hku/ecmd#2]
This is a very good job, providing us with data for algorithm verification. Thank you very much. However, I encountered some issues when trying to use `/camera_left/image_color/compressed `in the downloaded bag file. I couldn't view the images of this topic in RViz, although there is data when using the `rostopic echo` command. I attempted to convert the compressed image of type `sensor_msgs/CompressedImage` to `sensor_msgs/Image` using the following configuration in my launch file, but it still didn't work:
`<node name="image_transport" pkg="image_transport" type="republish" args="compressed in:=/camera_left/image_color/compressed raw out:=/camera_left/image_color" />`
I saw on Bilibili that you have successfully run lvi-sam's code using this dataset. Could you please guide me on how to modify it to work with this type of image data? Additionally, I couldn't find the noise parameters for IMU calibration. Could you tell me what the random walk noise parameters for the IMU are? Once again, thank you for your work!

**Comment by cpymaple** [comment]
Thanks for your interest.

1. When you re-play the rosbag, you can use the following command to convert ```sensor_msgs/CompressedImage ``` to ```sensor_msgs/Image``` type:
```
rosrun image_transport republish compressed in:=/camera_left/image_color raw out:=/camera_left/image_color
```

It seems that you need to revise your launch file based on the above command.

2. The IMU noise parameters are now available on our website for your reference (https://arclab-hku.github.io/ecmd/calibration/).

**Comment by coolaogege** [comment]
Thank you very much for your response. I have successfully used the dataset following your guidance.
