### ISSUE TITLE
Event Topic name

### ISSUE THREAD

**Issue by Hero9555** [arclab-hku/ecmd#4]
Hi, I've noticed that the type of events stream topics in the dataset is /dv_ros_msgs/EventArray, while the rpg_dvs_driver defines the type as /dvs_msgs/EventArray. Do you have any instructions on how to get around this? The dvs driver failed to recognize the message type.

**Comment by cpymaple** [comment]
Hi, The definition of /dv_ros_msgs/EventArray and /dvs_msgs/EventArray may exist in some different. You can read the event streams /dv_ros_msgs/EventArray, and change it to your target type.

**Comment by Hero9555** [comment]
> Hi, The definition of /dv_ros_msgs/EventArray and /dvs_msgs/EventArray may exist in some different. You can read the event streams /dv_ros_msgs/EventArray, and change it to your target type.

Hi, I have solved this by running a converting node. Thank you for the reply.
