### ISSUE TITLE
Some problems about Spatial Calibration

### ISSUE THREAD

**Issue by cs19469** [arclab-hku/ecmd#5]
Hello! Thank you for your wonderful work.
I observed that in the sensor settings, the infrared camera, RGB camera, and event camera are placed on the same horizontal line. How can I achieve precise spatial calibration of the three cameras?

**Comment by cpymaple** [comment]
Hi, You can get the spatial calibration of different cameras through "imu", for example, T_event_standard= T_event_imu * T_imu_standard. Besides, we provide the calibration rosbag so that you can use other suitable calibration methods to achieve camera calibration.

**Comment by cs19469** [comment]
Thanks for the help. Sorry for the delayed reply.
