### ISSUE TITLE
GNSS Receiver (Ublox F9P)Data

### ISSUE THREAD

**Issue by Erika1kuta** [arclab-hku/ecmd#7]
Hi, thanks for your great work on the ECMD dataset.

Your paper mentioned that your platform has two ublox gnss receiver, but I couldn't find any ublox related topics in the downloaded rosbag file. Have you collected their raw data? 

I'm looking forward to hearing back from you. Thank you very much.

**Comment by DarrenWong** [comment]
You can find the GNSS in RINEX format in the download link from the website
https://arclab-hku.github.io/ecmd/download/

**Comment by Erika1kuta** [comment]
Thanks. I found it.
