### ISSUE TITLE
关于论文中SLAM评估的小问题

### ISSUE THREAD

**Issue by huangfeng95** [arclab-hku/ecmd#8]
你好
感谢你们的工作！我看到论文中说到使用EVO对多种SLAM算法的精度进行了评估，指标为MPE，单位是百分比，请问具体是如何完成的呢？在EVO的介绍中我只看到无单位，m，角度和弧度的误差评估

**Comment by cpymaple** [comment]
你好，关于MPE的定义以及EVO的问题，可以参考以下链接: https://github.com/arclab-hku/Event_based_VO-VIO-SLAM/issues/5

**Comment by cpymaple** [comment]
> 你好 感谢你们的工作！我看到论文中说到使用EVO对多种SLAM算法的精度进行了评估，指标为MPE，单位是百分比，请问具体是如何完成的呢？在EVO的介绍中我只看到无单位，m，角度和弧度的误差评估

你好，关于MPE的定义以及EVO的问题，可以参考以下链接: https://github.com/arclab-hku/Event_based_VO-VIO-SLAM/issues/5

**Comment by huangfeng95** [comment]
> > 你好 感谢你们的工作！我看到论文中说到使用EVO对多种SLAM算法的精度进行了评估，指标为MPE，单位是百分比，请问具体是如何完成的呢？在EVO的介绍中我只看到无单位，m，角度和弧度的误差评估
> 
> 你好，关于MPE的定义以及EVO的问题，可以参考以下链接: [arclab-hku/Event_based_VO-VIO-SLAM#5](https://github.com/arclab-hku/Event_based_VO-VIO-SLAM/issues/5)

好的，感谢答疑！
