### ISSUE TITLE
Why do the pose data in the GT and the number of images in the Rosbag not match?

### ISSUE THREAD

**Issue by dyfffffer** [arclab-hku/ecmd#9]
In Dense_street_day_easy_a.bag, there are 2521 images but 126 data in gt. How to compute the pose completely?

**Comment by cpymaple** [comment]
> In Dense_street_day_easy_a.bag, there are 2521 images but 126 data in gt. How to compute the pose completely?

Hi, the frequency of images and GT is different. You can use interpolation or other methods to get a higher frequency of pose.

**Comment by dyfffffer** [comment]
Thank you for your prompt reply!
